version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: contacts_db
    environment:
      POSTGRES_DB: contacts_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: contacts_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build: .
    container_name: contacts_api
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/contacts_db
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  postgres_data: