version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: contacts_db
    environment:
      POSTGRES_DB: contacts_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: contacts_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    # image: serhiipalamarchuk/goit-pythonweb-hw-10:latest
    # Для локальної розробки використовуйте:
    build: .
    container_name: contacts_api
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://user:password@postgres:5432/contacts_db}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SERVER=${MAIL_SERVER}
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CORS_ORIGINS=${CORS_ORIGINS}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    # volumes:
    #   - .:/app
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: