services:
  - type: web
    name: contacts-api
    env: python
    buildCommand: "pip install poetry && poetry install"
    startCommand: "poetry run uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    plan: free
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: DATABASE_URL
        fromDatabase:
          name: contacts-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: contacts-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: MAIL_PORT
        value: 587
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CORS_ORIGINS
        value: "*"

databases:
  - name: contacts-db
    databaseName: contacts
    user: contacts_user
    plan: free

  - name: contacts-redis
    type: redis
    plan: free